spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
  cloud:
    stream:
      bindings:
        output:
          destination: order-exchange
        input:
          destination: order-result-exchange
          group: order-status-queue
